Watching for file changes with StatReloader
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Not Found: /sudha/assets1/favicon.svg
Not Found: /prasad/assets1/favicon.svg
Importing AvifImagePlugin
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 0 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 0 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Not Found: /users/setting/{% static 'assets/css/app.css
Not Found: /users/setting/{% static 'assets/css/core.css
Not Found: /users/www.googletagmanager.com/gtm5445.html
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 0 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 0 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Watching for file changes with StatReloader
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Not Found: /prasad/assets1/favicon.svg
Not Found: /assets1/favicon.svg
Importing AvifImagePlugin
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Not Found: /babar/assets1/favicon.svg
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Not Found: /sudha/assets1/favicon.svg
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 18075
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Not Found: /babar/assets1/favicon.svg
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Not Found: /undefined/
Not Found: /undefined/
Not Found: /babar/assets1/favicon.svg
Not Found: /.well-known/appspecific/com.chrome.devtools.json
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Watching for file changes with StatReloader
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\views.py changed, reloading.
Watching for file changes with StatReloader
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/pages/pages.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.pages_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /assets/data/api/users/users.json
Traceback (most recent call last):
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Django\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view post.views.users_json didn't return an HttpResponse object. It returned None instead.
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\PRASAD\Downloads\Desktop\narhe sP\post\views.py changed, reloading.
Watching for file changes with StatReloader
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Watching for file changes with StatReloader
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Returning 0 comments for post_id: 7f79df5b-8270-448d-b27e-c4d10dac7840
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Watching for file changes with StatReloader
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
Received request for comments on post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Returning 1 comments for post_id: 47bd3d60-f376-4213-969f-232d4ecbe4e4
Received request for comments on post_id: f26603c8-db69-4826-97ac-44bf326eff09
Returning 1 comments for post_id: f26603c8-db69-4826-97ac-44bf326eff09
